//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CA_Mini_Project_V4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public string ID { get; set; }
        public string Name { get; set; }
        public int Age { get; set; }
        public string Phone_Number { get; set; }
        public string Email { get; set; }
        public string Post_Code { get; set; }
        public string Gender { get; set; }
        public string Looking_For { get; set; }
        public string Interest_1 { get; set; }
        public string Interest_2 { get; set; }
        public string Interest_3 { get; set; }
    }
}
